blood_donation/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

from users.views import LoginView, LogoutView, ResetPasswordView, ForgotPasswordView, ResetConfirmView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('users.urls')),
    path("blood_request_value/", include('blood_request.urls')),

    # Reset password
    path('password-reset/<int:pk>/', ResetPasswordView.as_view(), name='password_reset'),
    #  Forget Password
    path('password-forgot/', ForgotPasswordView.as_view(), name='password_forgot'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='password/password_reset_done.html'
         ),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         ResetConfirmView.as_view(
             template_name='password/password_reset_confirm.html'
         ),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='password/password_reset_complete.html'
         ),
         name='password_reset_complete'),
    path('', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

blood_request/urls.py
from django.urls import path

from blood_request.views import ADDRequestView, getDonors, BloodRequestListView, AvailableDonorsMapViews, \
    DonorsListMapViews

app_name = 'blood_request'

urlpatterns = [
    path('add_request/', ADDRequestView.as_view(), name="add_request"),
    path('blood_requests_list/', BloodRequestListView.as_view(), name="blood_requests_list"),
    path('add_request/get_donors/', getDonors, name="get_donors"),
    path('available_donors/', AvailableDonorsMapViews.as_view(), name="available_donors"),
    path('donors/', DonorsListMapViews, name="donors")
]

users/urls.py
from django.urls import path

from users.views import DashboardView, SignUpView, get_cities_list_from_country

app_name = 'users'

urlpatterns = [
    path('dashboard/', DashboardView.as_view(), name="dashboard"),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('cities/', get_cities_list_from_country,
         name='cities_from_country'),
]

users/forms.py
from django import forms
from django.contrib.auth import get_user_model, password_validation
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm, PasswordChangeForm, SetPasswordForm
from django.core.exceptions import ValidationError
from django.forms import ModelForm, CharField, PasswordInput, ChoiceField
from django.utils.translation import gettext_lazy as _
from cities_light.models import City, Country

User = get_user_model()


# Sign Up Form
class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False, help_text='Optional',
                                 widget=forms.TextInput(attrs={'placeholder': 'First Name'}))
    last_name = forms.CharField(max_length=30, required=False, help_text='Optional',
                                widget=forms.TextInput(attrs={'placeholder': 'Last Name'}))
    email = forms.EmailField(max_length=254, help_text='Enter a valid email address',
                             widget=forms.TextInput(attrs={'placeholder': 'Email'}))
    mobile_number = forms.CharField(max_length=10, help_text='Enter a valid mobile number',
                             widget=forms.TextInput(attrs={'placeholder': 'Mobile Number'}))
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={'placeholder': 'Password'}))
    password2 = forms.CharField(label='Confirm Password', widget=forms.PasswordInput(attrs={'placeholder': 'Confirm Password'}))
    country = ChoiceField(required=False)
    city = ChoiceField(required=False)

    class Meta:
        model = User
        fields = [
            'username',
            'first_name',
            'last_name',
            'email',
            'mobile_number',
            'password1',
            'password2',
            'user_type',
            'blood_group',
            'country',
            'city',
            ]
        widgets = {
            'username': forms.TextInput(attrs={'placeholder': 'UserName'}),
            'country': forms.TextInput(attrs={'placeholder': 'Country'}),
            'city': forms.TextInput(attrs={'placeholder': 'City'}),
        }

    def __init__(self, *args, **kwargs):
        super(SignUpForm, self).__init__(*args, **kwargs)
        self.fields["blood_group"].choices = [("", "Select")] + list(
            User.BloodGroupStatus.choices)
        self.fields["country"].choices = [("", "Select")] + list(
            Country.objects.values_list('name', 'name'))
        self.fields["city"].choices = [("", "Select")] + list(
            City.objects.values_list('name', 'name'))

    def save(self, commit=True):
        """
        this function used to save user's instance with making password in hash
         format,and it is also assign email to username
        """
        # Save the provided password in hashed format
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        user.raw_password = self.cleaned_data["password1"]
        user.username = self.cleaned_data['email'].lower()
        user.email = self.cleaned_data['email'].lower()
        if commit:
            user.save()
        return user


class UserLoginForm(AuthenticationForm):
    """form for the user login."""

    username = forms.CharField()

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.error_messages.update({
            "invalid_login": 'Invalid Login'
        })

    def clean_username(self):
        """validate username."""
        return self.cleaned_data['username'].lower()


class PasswordChangeForm(PasswordChangeForm):
    def clean_new_password2(self):
        password1 = self.cleaned_data.get("new_password1")
        password2 = self.cleaned_data.get("new_password2")
        old_password = self.cleaned_data.get("old_password")
        if password1 and password2:
            if password1 != password2:
                raise ValidationError(
                    self.error_messages["password_mismatch"],
                    code="password_mismatch",
                )
            elif old_password and (password1 == old_password):
                self.add_error("new_password2", "same password please")
        password_validation.validate_password(password2, self.user)
        return password2


class ResetPasswordForm(ModelForm):
    """
    This form is used to validate old password
    validate new and confirm password
    if above both validations passed then it will set new password
    """
    password1 = CharField(label='Password', widget=PasswordInput(attrs={'placeholder': 'Password'}))
    confirm_password = CharField(label='Confirm Password',
                                 widget=PasswordInput(attrs={'placeholder': 'Confirm Password'}))
    old_password = CharField(label='Old Password', widget=PasswordInput(attrs={'placeholder': 'Old Password'}))

    class Meta:
        """
        this is META class for password reset form
        """
        model = User
        fields = ('confirm_password',
                  'old_password',
                  'password1',)
        widgets = {
            "confirm_password": forms.TextInput(
                attrs={
                    "placeholder": "Enter Confirm Password",
                }
            ),
            "old_password": forms.TextInput(
                attrs={
                    "placeholder": "Enter Old Password",
                }
            ),
            "password1": forms.TextInput(
                attrs={
                    "placeholder": "Enter New Password",
                }
            ),
        }

    def clean_password1(self):
        """
        this function used for validating user's password
        """
        password = self.cleaned_data.get("password1")
        confirm_password = self.data.get("confirm_password")
        if password and confirm_password:
            if password != confirm_password:
                # raise error
                self.add_error('confirm_password', "Confrim passworkd")
        # check validations for password
        # error = validate_password(password)
        # if error:
        #     self.add_error('confirm_password', error)
        return password

    def clean_old_password(self):
        """
        this function used for validating user's old password
        """
        old_password = self.data.get("old_password")
        new_password = self.data.get("password1")
        if old_password == new_password:
            self.add_error('password1', "same please")
        if old_password and not self.instance.check_password(old_password):
            self.add_error('old_password', "old not match with new")
        else:
            return old_password

    def save(self, commit=True):
        """
        this function used to save user's password
        """
        # Save the provided password in hashed format
        self.instance.set_password(self.cleaned_data["password1"])
        self.instance.raw_password = self.cleaned_data["password1"]
        self.instance.save()


class CustomResetConfirmViewForm(SetPasswordForm):
    new_password1 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'New Password'}))
    error_messages = {
        "password_mismatch": _("Password does not match."),
    }
    new_password2 = forms.CharField(
        label=_("Confirm Password"),
        strip=False,
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password", 'placeholder': 'Confirm New Password'}),
    )

users/views.py
from http import HTTPStatus

from cities_light.models import City
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import PasswordResetForm
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import Group
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView, PasswordChangeView, \
    PasswordResetConfirmView, INTERNAL_RESET_SESSION_TOKEN
from django.contrib.messages.views import SuccessMessageMixin
from django.core.exceptions import ImproperlyConfigured
from django.http.response import HttpResponseRedirect, JsonResponse
from django.shortcuts import render, resolve_url, redirect
from django.urls import reverse_lazy, reverse
from django.utils.decorators import method_decorator
from django.views.decorators.cache import never_cache
from django.views.decorators.debug import sensitive_post_parameters
from django.views.generic import CreateView
from django.views.generic.base import TemplateView, View

from blood_donation import settings
from users.forms import SignUpForm, UserLoginForm, PasswordChangeForm, CustomResetConfirmViewForm
from users.utils import message_display_func


# Create your views here.
class DashboardView(LoginRequiredMixin, TemplateView):
    template_name = 'Dashboard.html'


class LoginView(SuccessMessageMixin, LoginView):
    template_name = 'login.html'
    authentication_form = UserLoginForm
    success_message = 'Login Successfully'
    redirect_authenticated_user = True

    def get_default_redirect_url(self):
        """Return the default redirect URL."""
        return resolve_url(self.next_page or settings.LOGIN_REDIRECT_URL)


class LogoutView(LoginRequiredMixin, LogoutView):
    """Logout View"""


# Sign Up View
class SignUpView(CreateView):
    form_class = SignUpForm
    success_url = reverse_lazy('login')
    template_name = 'signin.html'

    def form_valid(self, form):
        """
        This method will be used for validating forms.
        """
        context = self.get_context_data()
        form = context['form']
        # resource data validation as form at time of creating user object
        user = form.save()
        user_group = Group.objects.get(
            name__icontains=self.request.POST.get('user_type'))
        user.groups.add(user_group)
        user.user_permissions.set(user_group.permissions.all())
        user.save()
        user = {
            'id': user.id, 'email': user.email,
            'first_name': user.first_name,
            'last_name': user.last_name,
            'password': user.password,
            'confirm_password': user.password,
            'user_type': user.user_type,
            'mobile_number': user.mobile_number,
        }
        django_messages = message_display_func(self.request, "Register successfully")
        data = {
            "status": "success",
            "user": user,
            "messages": django_messages,
            'redirect_url': reverse_lazy('users:dashboard'),
        }
        return JsonResponse(data, status=201)

    def form_invalid(self, form):
        data = {
            "status": "error",
            "errors": dict(form.errors)
        }
        return JsonResponse(data, status=HTTPStatus.BAD_REQUEST)


class ForgotPasswordView(SuccessMessageMixin, PasswordResetView, TemplateView,
                         View):
    """class for password forgot."""
    extra_email_context = {
        "site_url": settings.SITE_URL
    }
    template_name = 'password/password_forgot.html'
    html_email_template_name = 'emails/password_reset_email.html',
    subject_template_name = 'emails/password_reset_subject'
    success_url = reverse_lazy('password_reset_done')
    form_class = PasswordResetForm
    site_url = settings.SITE_URL

    def form_valid(self, form):
        """form valid method, check that email address is exists or not."""
        if self.request.method == "POST":
            user_email = self.request.POST.get('email')
            registered_email = get_user_model().objects.filter(
                email=user_email)
            if not registered_email.exists():
                messages.error(self.request, "Email Invalid Messages")
                return redirect('password_forgot')
            messages.success(self.request, "Link send success fully,Please check your inbox.")
        return super().form_valid(form)


class ResetPasswordView(SuccessMessageMixin, PasswordChangeView):
    """class for password reset."""
    template_name = 'password/password_reset.html'
    success_url = reverse_lazy('logout')
    site_url = settings.SITE_URL
    form_class = PasswordChangeForm
    success_message = "Password changed successfully"


class ResetConfirmView(SuccessMessageMixin, PasswordResetConfirmView):
    form_class = CustomResetConfirmViewForm
    success_message = "Password changed successfully"

    @method_decorator(sensitive_post_parameters())
    @method_decorator(never_cache)
    def dispatch(self, *args, **kwargs):
        self.user = self.get_user(kwargs["uidb64"])
        if self.user != self.request.user and not self.request.user.is_anonymous:
            messages.error(self.request,
                           "other user's password can't change")
            return HttpResponseRedirect(
                reverse('users:dashboard'))
        if "uidb64" not in kwargs or "token" not in kwargs:
            raise ImproperlyConfigured(
                "The URL path must contain 'uidb64' and 'token' parameters."
            )

        self.validlink = False
        self.user = self.get_user(kwargs["uidb64"])

        if self.user == self.request.user:
            messages.error(self.request,
                           "user reset password error")
            return HttpResponseRedirect(
                reverse('users:dashboard'))

        if self.user is not None:
            token = kwargs["token"]
            if token == self.reset_url_token:
                session_token = self.request.session.get(
                    INTERNAL_RESET_SESSION_TOKEN)
                if self.token_generator.check_token(self.user, session_token):
                    # If the token is valid, display the password reset form.
                    self.validlink = True
                    return super().dispatch(*args, **kwargs)
            elif self.token_generator.check_token(self.user, token):
                # Store the token in the session and redirect to the
                # password reset form at a URL without the token. That
                # avoids the possibility of leaking the token in the
                # HTTP Referer header.
                self.request.session[INTERNAL_RESET_SESSION_TOKEN] = token
                redirect_url = self.request.path.replace(
                    token, self.reset_url_token
                )
                return HttpResponseRedirect(redirect_url)
        messages.error(self.request, "Link is not valid")
        return HttpResponseRedirect(
            reverse('users:dashboard'))


def get_cities_list_from_country(request):
    """
    This function used to get all cities name after user select country
    """
    if request.method == 'GET' and request.GET.get('country'):
        cities = City.objects.filter(country__name=request.GET.get('country'))
        data = [("", "Select")] + list(cities.values_list('name', 'name'))
        return JsonResponse({'cities': data})
    return JsonResponse({'cities': [("", "Select")]})

users/templates/Dashboard.html
{% extends 'base.html' %}
{% load static %}
{% block content%}

<div id="background-wrap">
    <div class="bubble x1"></div>
    <div class="bubble x2"></div>
    <div class="bubble x3"></div>
    <div class="bubble x4"></div>
    <div class="bubble x5"></div>
    <div class="bubble x6"></div>
    <div class="bubble x7"></div>
    <div class="bubble x8"></div>
    <div class="bubble x9"></div>
    <div class="bubble x10"></div>
</div>
    <!--===== HOME =====-->
<section class="home responsive-font-example" id="home">
    <div class="home__container bd-grid responsive-font-example">
        <div class="home__img responsive-font-example">
            <img src="{% static 'images/12-removebg-preview.png' %}" alt="" data-speed="-2" class="move">
            <img src="{% static 'images/blood2-removebg-preview.png' %}" alt="" data-speed="-2" class="move">
        </div>

        <div class="home__data responsive-font-example">
            <h1 class="home__title responsive-font-example">Blood<br> Donation</h1>
            <p class="home__description responsive-font-example">Be the reason for someone’s heartbeat. <br> You can become a superhero too. Just donate a bag of blood.</p>
            <a href="#" class="home__button responsive-font-example">Get Started</a>
        </div>
    </div>
</section>
<div id="background-wrap">
    <div class="bubble x1"></div>
    <div class="bubble x2"></div>
    <div class="bubble x3"></div>
    <div class="bubble x4"></div>
    <div class="bubble x5"></div>
    <div class="bubble x6"></div>
    <div class="bubble x7"></div>
    <div class="bubble x8"></div>
    <div class="bubble x9"></div>
    <div class="bubble x10"></div>
</div>
<!--animation start-->
<div class="wrapper">
    <div class="box1">
        <p><b>Blood Donation</b></p>
    </div>
    <div class="box5 responsive-font-example">
        <p class="responsive-font-example">Be the reason for someone’s heartbeat. Donate blood. Not on roads but in blood donation camps.
            A single drop of blood can make a huge difference. The gift of blood is a gift to someone’s life</p>
    </div>
</div>
<div id="background-wrap">
    <div class="bubble x1"></div>
    <div class="bubble x2"></div>
    <div class="bubble x3"></div>
    <div class="bubble x4"></div>
    <div class="bubble x5"></div>
    <div class="bubble x6"></div>
    <div class="bubble x7"></div>
    <div class="bubble x8"></div>
    <div class="bubble x9"></div>
    <div class="bubble x10"></div>
</div>
<!--animation end-->
<div class="flip-card">
  <div class="flip-card-inner">
    <div class="flip-card-front">
      <img src="{% static 'images/blood1.jpg' %}" alt="Avatar" style="width:300px;height:300px;">
    </div>
    <div class="flip-card-back">
      <img src="{% static 'images/blood1.jpg' %}" alt="Avatar" style="width:300px;height:300px;">
    </div>
  </div>
</div>

<!-- section start -->
<section class="sec-10">
    <div class="container">
        <h2 class="main-title">Every blood donation is a gift of life.</h2>
        <div class="content">
            <div class="image">
                <img src="{% static 'images/blood34.png' %}">
            </div>
            <div class="text-box">
                <h3>Blood Donation</h3>
                <p>Blood donation is a vital part of worldwide healthcare.
                    It relates to blood
                    transfusion as a life-sustaining and life-saving procedure
                    as well as a form of therapeutic phlebotomy as a primary
                    medical intervention. Over one hundred million units of
                    blood are donated each year throughout the world.</p>
            </div>
        </div>
        <div class="media-icons">
            <a href="#" class="icon"><i class="fab fa-facebook"></i></a>
            <a href="#" class="icon"><i class="fab fa-instagram"></i></a>
            <a href="#" class="icon"><i class="fab fa-twitter"></i></a>
            <a href="#" class="icon"><i class="fab fa-youtube"></i></a>
        </div>
    </div>
</section>
<!--section end-->
<section class="sec-02">
    <div class="container">
        <h3 class="section-title">Blood donation</h3>
        <div class="content">
            <div class="image">
                <img src="{% static 'images/blood1.jpg' %}">
            </div>
            <div class="info">
                <h4 class="info-title">Description</h4>
                <p>Blood donation is a vital part of worldwide healthcare.
                    It relates to blood
                    transfusion as a life-sustaining and life-saving procedure
                    as well as a form of therapeutic phlebotomy as a primary
                    medical intervention. Over one hundred million units of
                    blood are donated each year throughout the world.</p>
            </div>
        </div>
    </div>
</section>
<section class="sec-03">
    <div class="container">
        <h3 class="section-title">Blood Donation</h3>
        <div class="content">
            <div class="media-info">
                <li><a href="#"><i class="fab fa-facebook"></i> Facebook</a></li>
                <li><a href="#"><i class="fab fa-instagram"></i> instagram</a></li>
                <li><a href="#"><i class="fab fa-twitter"></i> Twitter</a></li>
                <li><a href="#"><i class="fab fa-linkedin"></i> Linked-in</a></li>
                <li><a href="#"><i class="fab fa-whatsapp"></i> Whatsapp</a></li>
            </div>
            <div class="image">
                <img src="{% static 'images/blood1.jpg' %}">
            </div>
        </div>
    </div>
</section>


{%endblock%}

users/templates/base.html
<!DOCTYPE html>
{% load static %}
<!--html start-->
<html lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% include 'head.html' %}
    {% block head %}{% endblock %}
</head>
<body>
{% block body %}
<!-- header -->
{% include 'header.html' %}

{% block javascript %}
<script type="text/javascript" src="{% static 'js/jquery-3.2.1.min.js' %}"></script>

{% endblock %}
<!-- Sidebar and content section start-->
<main>
    <div class="inner-wrapper header-spacing-from-card">
        <!-- Sidebar starts -->

        <!-- Sidebar ends -->
        <!-- main content start-->
        <div class="main-content">
            {% block content %}
            {% endblock %}
        </div>
        <!-- main content ends-->
    </div>
</main>

{% include 'footer.html' %}
<div class="loader">
</div>
{% endblock body %}
{% block scripts %}
{% endblock %}
</body>
</html>
<!--html end-->

users/templates/header.html
{% load static %}
<!-- Header starts -->
<div id="background-wrap">
    <div class="bubble x1"></div>
    <div class="bubble x2"></div>
    <div class="bubble x3"></div>
    <div class="bubble x4"></div>
    <div class="bubble x5"></div>
    <div class="bubble x6"></div>
    <div class="bubble x7"></div>
    <div class="bubble x8"></div>
    <div class="bubble x9"></div>
    <div class="bubble x10"></div>
</div>
<!--===== HEADER =====-->
<header class="l-header">
    <nav class="nav bd-grid">
        <div>
            <a href="{% url 'users:dashboard' %}" class="nav__logo">BloodDonation</a>
        </div>

        <div class="nav__toggle" id="nav-toggle">
            <i class='bx bx-menu'></i>
        </div>

        <div class="nav__menu" id="nav-menu">
            <div class="nav__close" id="nav-close">
                <i class='bx bx-x'></i>
            </div>
            {% if request.user.is_authenticated %}
            <ul class="nav__list">
                <li class="nav__item"><a href="{% url 'blood_request:blood_requests_list' %}" class="nav__link active">Request</a></li>
                <li class="nav__item"><a href="{% url 'blood_request:available_donors' %}" class="nav__link">About</a></li>
                <li class="nav__item"><a href="#contact" class="nav__link">Contact</a></li>
                <li class="nav__item"><a href="{% url 'logout' %}" class="nav__link">Logout</a></li>
            </ul>
            {% endif %}
        </div>
    </nav>
</header>
<!-- Header ends -->

users/templates/login.html
<html>
{% load static %}
<style>
    /* Importing fonts from Google */
@import url('https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700;800;900&display=swap');

/* Reseting */
* {
    margin: 0;
    padding: 0;
    box-sizing: border-box;
    font-family: 'Poppins', sans-serif;
}

body {
    background: #ecf0f3;
}

.wrapper {
    max-width: 350px;
    min-height: 500px;
    margin: 80px auto;
    padding: 40px 30px 30px 30px;
    background-color: #ecf0f3;
    border-radius: 15px;
    box-shadow: 13px 13px 20px #cbced1, -13px -13px 20px #fff;
}

.logo {
    width: 80px;
    margin: auto;
}

.logo img {
    width: 100%;
    height: 80px;
    object-fit: cover;
    border-radius: 50%;
    box-shadow: 0px 0px 3px #5f5f5f,
        0px 0px 0px 5px #ecf0f3,
        8px 8px 15px #a7aaa7,
        -8px -8px 15px #fff;
}

.wrapper .name {
    font-weight: 600;
    font-size: 1.4rem;
    letter-spacing: 1.3px;
    padding-left: 10px;
    color: #B41919;
}

.wrapper .form-field input {
    width: 100%;
    display: block;
    border: none;
    outline: none;
    background: none;
    font-size: 1.2rem;
    color: #666;
    padding: 10px 15px 10px 10px;
    /* border: 1px solid red; */
}

.wrapper .form-field {
    padding-left: 10px;
    margin-bottom: 20px;
    border-radius: 20px;
    box-shadow: inset 8px 8px 8px #cbced1, inset -8px -8px 8px #fff;
}

.wrapper .form-field .fas {
    color: #555;
}

.wrapper .btn {
    box-shadow: none;
    width: 100%;
    height: 40px;
    background-color: #B41919;
    color: #fff;
    border-radius: 25px;
    box-shadow: 3px 3px 3px #b1b1b1,
        -3px -3px 3px #fff;
    letter-spacing: 1.3px;
}

.wrapper .btn:hover {
    background-color: #B41919;
}

.wrapper a {
    text-decoration: none;
    font-size: 0.8rem;
    color: #B41919;
}

.wrapper a:hover {
    color: #B41919;
}

@media(max-width: 380px) {
    .wrapper {
        margin: 30px 20px;
        padding: 40px 15px 15px 15px;
    }
}
.wrapper .input-group-addon.psw-ic img {
    display: none;
}

.wrapper .input-group-addon.psw-ic img:first-child {
    display: block;
}
.wrapper .input-group-addon.psw-show img:first-child {
    display: none;
}

.wrapper .input-group-addon.psw-show img:last-child {
    display: block;
}
.wrapper .input-group-addon.psw-ic img {
    margin-left: 240px;
    margin-top: -16px;
}
.error_class{
    color: #B41919;
}
</style>
<body>
<div class="wrapper">
<div class="logo">
    <img src="{% static 'images/bloodbanklogo.png' %}" alt="">
</div>
<div class="text-center mt-4 name bloodbank-name-color">
    BloodBank
</div>
{% if form.non_field_errors %}
    {% for error in form.non_field_errors %}

    <div class=" text-danger error_class">
        <small>{{ error }}</small>

    </div>
    {% endfor %}
{% endif %}
<br>
<form class="p-3 mt-3" method="post" id="login_form" action="{% url 'login' %}">
    {% csrf_token %}
    <div class="form-field d-flex align-items-center">
        <span class="far fa-user"></span>
        <input type="text" name="username" id="{{ form.username.auto_id }}" placeholder="Username">
        {% if form_field.errors %}
            {% for error in form.username.errors %}
                <span id="{{ form.username.auto_id }}" class="error text-danger error_class">{{ error }}</span>
            {% endfor %}

        {% endif %}
    </div>
    <div class="form-field d-flex align-items-center">
        <span class="fas fa-key"></span>
        <input type="password" name="password" class="password_ip" id="{{ form.password.auto_id }}" placeholder="Password">
        <span class="btn input-group-addon psw-ic">
            <img src="{% static 'images/eye-icon-hide.svg' %}" alt="Eye">
            <img src="{% static 'images/eye-icon-show.svg' %}" alt="Eye">
        </span>
        {% if form.password.errors %}
            {% for error in form.password.errors %}
                <span id="" class="error text-danger error_class">{{ error }}</span>
            {% endfor %}
        {% endif %}
    </div>
    <button class="btn mt-3">Login</button>
</form>
<div class="text-center fs-6">
    <a href="{% url 'password_forgot' %}">Forget password?</a> or <a href="{% url 'users:signup' %}">Sign up</a>
</div>
</div>
<!-- SCRIPTS -->
<script type="text/javascript" src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/jquery.cookie.js' %}"></script>

<!-- Bootstrap core JavaScript -->
<script type="text/javascript" src="{% static 'js/popper.min.js' %}"></script>
<script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>

<!-- multiselect js -->
<script src="{% static 'js/chosen.jquery.js' %}"></script>
<script type="text/javascript">
$(document).ready(function(){
    $( "span.input-group-addon" ).click(function() {
        $(this).toggleClass("psw-show");
        var password = $(this).prev('input#{{form.password.auto_id}}');
        if (password.attr('type') == 'text'){
            password.attr('type', 'password');
        }
        else{
            password.attr('type', 'text');
        }
    });
});
</script>
</body>
</html>