blood_donation/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views

from users.views import LoginView, LogoutView, ResetPasswordView, ForgotPasswordView, ResetConfirmView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include('users.urls')),
    path("blood_request_value/", include('blood_request.urls')),

    # Reset password
    path('password-reset/<int:pk>/', ResetPasswordView.as_view(), name='password_reset'),
    #  Forget Password
    path('password-forgot/', ForgotPasswordView.as_view(), name='password_forgot'),
    path('password-reset/done/',
         auth_views.PasswordResetDoneView.as_view(
             template_name='password/password_reset_done.html'
         ),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         ResetConfirmView.as_view(
             template_name='password/password_reset_confirm.html'
         ),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(
             template_name='password/password_reset_complete.html'
         ),
         name='password_reset_complete'),
    path('', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
]

blood_request/urls.py
from django.urls import path

from blood_request.views import ADDRequestView, getDonors, BloodRequestListView, AvailableDonorsMapViews, \
    DonorsListMapViews

app_name = 'blood_request'

urlpatterns = [
    path('add_request/', ADDRequestView.as_view(), name="add_request"),
    path('blood_requests_list/', BloodRequestListView.as_view(), name="blood_requests_list"),
    path('add_request/get_donors/', getDonors, name="get_donors"),
    path('available_donors/', AvailableDonorsMapViews.as_view(), name="available_donors"),
    path('donors/', DonorsListMapViews, name="donors")
]

users/urls.py
from django.urls import path

from users.views import DashboardView, SignUpView, get_cities_list_from_country

app_name = 'users'

urlpatterns = [
    path('dashboard/', DashboardView.as_view(), name="dashboard"),
    path('signup/', SignUpView.as_view(), name='signup'),
    path('cities/', get_cities_list_from_country,
         name='cities_from_country'),
]

blood_request/models.py
from auditlog.registry import auditlog
from django.db import models
from django.db.models.deletion import CASCADE
from django_extensions.db.models import ActivatorModel, TimeStampedModel
from django.contrib.auth import get_user_model
from django.utils.translation import gettext_lazy as _

User = get_user_model()

ACCEPTED_TEXT = "Accept"
ACCEPTED_KEY = "accept"
REJECTED_TEXT = "Reject"
REJECTED_KEY = "reject"
PENDING_TEXT = "Pending"
PENDING_KEY = "pending"


# Create your models here
class BloodRequest(TimeStampedModel, ActivatorModel):
    """blood request model"""

    class RequestStatus(models.TextChoices):
        """
        This class provides choice of user that which type of user it is
        example: Admin, Donor, Receiver
        """

        ACCEPTED = ACCEPTED_KEY, _(ACCEPTED_TEXT)
        REJECTED = REJECTED_KEY, _(REJECTED_TEXT)
        PENDING = PENDING_KEY, _(PENDING_TEXT)

    receiver = models.ForeignKey(User,  on_delete=CASCADE, related_name='blood_requester')
    donor = models.ForeignKey(User, on_delete=CASCADE, related_name='blood_donor')
    hospital = models.ForeignKey(User, on_delete=CASCADE, related_name='hospital')
    units = models.CharField(max_length=15)
    request_status = models.CharField(max_length=15, choices=RequestStatus.choices)

    def __str__(self):
        return self.receiver.username


auditlog.register(BloodRequest)

blood_request/forms.py
from django import forms
from django.forms.models import ModelForm

from blood_request.models import BloodRequest
from users.models import User


class BloodRequestCreateForm(ModelForm):
    units = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Units'}))
    blood_group_value = forms.ChoiceField()

    class Meta:
        model = BloodRequest
        fields = ('donor', 'units', 'hospital', 'blood_group_value', )
        exclude = ('receiver', 'request_status')

    def __init__(self, *args, **kwargs):
        super(BloodRequestCreateForm, self).__init__(*args, **kwargs)
        self.fields["donor"].choices = User.donors_filters()
        self.fields["hospital"].choices = User.hospitals_filters()
        self.fields['blood_group_value'].choices = User.blood_groups_filters()


class BloodRequestFilterForm(forms.ModelForm):
    search = forms.CharField(required=False)

    class Meta:
        model = BloodRequest
        fields = [
            "request_status",
        ]

    def __init__(self, *args, **kwargs):
        super(BloodRequestFilterForm, self).__init__(*args, **kwargs)
        # self.fields["first_name"].choices = User.first_name_filters()
        # self.fields["last_name"].choices = User.last_name_filters()
        self.fields["request_status"].choices = [("",
                                                  "Select")] + BloodRequest.RequestStatus.choices

blood_request/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models.query import QuerySet
from django.http.response import JsonResponse, HttpResponseRedirect
from django.urls import reverse
from django.views.generic import TemplateView
from django.views.generic.edit import CreateView
from django.views.generic.list import ListView

from blood_request.filters import BloodRequestFilter
from blood_request.forms import BloodRequestCreateForm
from blood_request.models import BloodRequest
from users.models import User
from blood_request.utils import send_mail_to_donor


# Create your views here.
class ADDRequestView(LoginRequiredMixin, CreateView):
    template_name = 'add_request.html'
    form_class = BloodRequestCreateForm
    model = BloodRequest

    def get_success_url(self):  # new
        return reverse('users:dashboard')

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.receiver_id = self.request.user.id
        self.object.request_status = BloodRequest.RequestStatus.PENDING
        self.object.save()
        send_mail_to_donor.delay(
            request_id=self.object.id,
            subject="Blood Request",
            text_body='emails/blood_request.txt',
            email_template='emails/blood_request.html',
        )
        return HttpResponseRedirect(self.get_success_url())


class AvailableDonorsMapViews(TemplateView):
    template_name = "available_donors_map.html"


def getDonors(request):
    blood_group_value = request.GET.get("blood_group_value")
    donors = User.objects.filter(blood_group=blood_group_value, user_type=User.UserType.DONOR)
    donors = [(donor.username, donor.id) for donor in donors]
    response_data = {
        "donors": donors
    }
    return JsonResponse(response_data)


def DonorsListMapViews(request):
    """
    get available donors
    """
    available_donors = User.objects.filter(user_type=User.UserType.DONOR)
    from geopy.geocoders import Nominatim
    geolocator = Nominatim(user_agent='users')
    county_city_list = [country for country in available_donors.values_list('city', 'country').exclude(city=None, country=None)]
    county_city_list_ids = [id for id in available_donors.values_list('id').exclude(city=None, country=None)]
    loc_list = [geolocator.geocode(i[0] + ',' + i[1]) for i in county_city_list]
    points = [(loc.latitude, loc.longitude) for loc in loc_list]
    geo_json = [{
                'type': 'Feature',
                'geometry': {
                    'type': 'Point',
                    'coordinates': [lon[1], lon[0]]
                },
                'properties': {
                    'title': 'Mapbox SF'
                },
                } for lon in points]
    response = {
        "available_donors_points": geo_json,
        "cities": county_city_list
    }
    return JsonResponse(response)


class BloodRequestListView(ListView):
    """class for blood requests list."""
    model = BloodRequest
    template_name = 'blood_requests_list.html'
    paginate_by = 2
    ordering = ["-created"]

    def get_queryset(self, **kwargs) -> QuerySet:
        queryset = self.model.objects.all()
        if self.request.user.user_type == User.UserType.DONOR:
            queryset = queryset.filter(donor=self.request.user)
        queryset_filter = BloodRequestFilter(data=self.request.GET,
                                             request=self.request,
                                             queryset=queryset)
        self.filter_form = queryset_filter.form
        order_by = self.request.GET.get("order_by", "-created")
        return queryset_filter.qs.order_by(order_by)

    def get_paginate_by(self, queryset):
        """
        Get the number of items to paginate by, or ``None`` for no pagination.
        """
        self.paginate_by = self.request.GET.get('paginate_by',
                                                self.paginate_by)
        return self.paginate_by

    # pass dictionary of form objects of all users into the template
    # with user.id as key and form object as its value
    def get_context_data(self, *args, object_list=None, **kwargs) -> dict:
        context = super().get_context_data(*args, **kwargs)
        context["blood_request_filter"] = self.filter_form
        return context

blood_request/templates/add_request.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}
{% block content %}
<div class="wrapper wrapper-form">
<div class="logo">
    <img src="{% static 'images/bloodbanklogo.png' %}" alt="">
</div>
    <br>
<div class="text-center name bloodbank-name-color">
Make Request
</div>
<br>
<p class="login-box-msg login-middle-content text-center">Request for blood to available donor</p>
<br>
<form class="p-3 mt-3" method="post" action="{% url 'blood_request:add_request' %}" novalidate>
    {% csrf_token %}
        {% include "partials/add_request_partial.html" with field=form.blood_group_value  %}
        {% include "partials/add_request_partial.html" with field=form.donor %}
        {% include "partials/add_request_partial.html" with field=form.hospital %}
        {% include "partials/add_request_partial.html" with field=form.units %}

    <button type="submit" class="btn mt-3 submit-button-style">Add Request</button>
</form>
<div class="text-center fs-6">
    <a href="{% url 'blood_request:blood_requests_list' %}">Back</a>
</div>
</div>
{% endblock %}

blood_request/templates/available_donors_map.html
{% extends 'base.html' %}
{% load static %}
{% block content%}
<title>Available Donors</title>
<body>
<div id="map"></div>

{% endblock %}
<!--

blood_request/templates/blood_requests_list.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}
{% load clients_templatetags %}
{% block content %}
<div class="wrapper wrapper-form">
<div class="logo">
    <img src="{% static 'images/bloodbanklogo.png' %}" alt="">
</div>
    <br>
<div class="text-center name bloodbank-name-color">
Blood Request Lists
</div>
<br>
<p class="login-box-msg login-middle-content text-center">Request for blood to available donor</p>
<br>
<div class="container">
    <div class="row">
        <div class="col-lg-10 mx-auto">
            <div class="career-search mb-60">

                <form class="career-form mb-60">
                    <div class="row">
                        <div class="col-md-6 col-lg-3 my-3">
                            <div class="input-group position-relative">
                            {% render_field blood_request_filter.search class="form-control" placeholder="Search here" %}
                            </div>
                        </div>
                         {% include 'partials/add_select_filter.html' with field_name='Request Status' filter_filed_value=blood_request_filter.request_status.html_name filter_id_value=blood_request_filter.request_status.id_for_label filter_choices=blood_request_filter.fields.request_status.choices key_condition_check=request.GET.dict.request_status %}
                        <div class="col-md-6 col-lg-3 my-3 margin-search-button">
                            <button type="submit" class="btn btn-lg btn-block btn-light btn-custom button-width-set" id="contact-submit">
                                Search
                            </button>
                        </div>
                        <div class="col-md-6 col-lg-3 my-3">
                           <a href="{% url 'blood_request:add_request' %}" class="btn btn-primary add-request-button"> <img src="{% static 'images/plus-icon.svg' %}"> Add
                        Request</a>
                        </div>
                    </div>
                </form>

                {% if object_list %}
                <div class="filter-result">
                    <p class="mb-30 ff-montserrat"></p>
                    {% for user in object_list %}
                    <div class="job-box d-md-flex align-items-center justify-content-between mb-30">
                        <div class="job-left my-4 d-md-flex align-items-center flex-wrap">
                            <div class="img-holder mr-md-4 mb-md-0 mb-4 mx-auto mx-md-0 d-md-none d-lg-flex">
                                {{user.donor.blood_group}}
                            </div>
                            <div class="job-content">
                                <h5 class="text-center text-md-left text-margin-username">{{user.donor.username}}</h5>
                                <ul class="d-md-flex flex-wrap text-capitalize ff-open-sans">
                                    <li class="mr-md-4">
                                        <i class="zmdi zmdi-pin mr-2"></i> {{user.hospital.username}}
                                    </li>
                                    <li class="mr-md-4">
                                        <i class="zmdi zmdi-phone mr-2"></i> {{user.mobile_number}}
                                    </li>
                                    <li class="mr-md-4">
                                        {% if user.request_status == 'pending' %}
                                            <h6 class="mb-0"><span class="badge bg-danger">{{user.request_status}}</span></h6>
                                        {% elif user.request_status == 'accept' %}
                                            <h6 class="mb-0"><span class="badge bg-success">{{user.request_status}}</span></h6>
                                        {% elif user.request_status == 'reject' %}
                                            <h6 class="mb-0"><span class="badge bg-warning">{{user.request_status}}</span></h6>
                                        {% endif %}
                                    </li>
                                </ul>
                            </div>
                        </div>
                        <div class="job-right my-4 flex-shrink-0">
                            <a href="#" class="btn d-block w-100 d-sm-inline-block btn-light request-status-btn-height">Apply now</a>
                        </div>
                    </div>
                    {% endfor %}
                </div>
                {% else %}
                <div class="no-user-page flex-container margin-main-no-data-div">
                    <div class="empty-page-content">
                        <div class="img">
                            <img class="sidebar-panel-img margin-for-image-no-data" src="{% static 'images/empty-icon.svg' %}" alt="Empty">
                        </div>
                        <p>There’re no user data found !</p>
                    </div>
                </div>
                {% endif %}
            </div>

            <!-- START Pagination -->
            {% if page_obj %}
            <nav aria-label="Page navigation">
                <ul class="pagination pagination-reset justify-content-center">
                    {% if page_obj.has_previous %}
                    <li class="page-item">
                        <a class="page-link" href="?{% url_add_query request page=page_obj.previous_page_number %}" tabindex="-1" aria-disabled="true">
                            <i class="zmdi zmdi-long-arrow-left"></i>
                        </a>
                    </li>
                    {% endif %}
                    {% for num in page_obj.paginator.page_range %}
                          {% if page_obj.number == num %}
                                <li class="page-item"><a class="page-link">{{num}}</a></li>
                          {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
                                <li class="page-item d-none d-md-inline-block"><a class="page-link" href="?{% url_add_query request page=num %}">{{num}}</a></li>
                          {% endif %}
                    {% endfor %}
                    {% if page_obj.has_next %}
                    <li class="page-item">
                        <a class="page-link" href="?{% url_add_query request page=page_obj.next_page_number %}">
                            <i class="zmdi zmdi-long-arrow-right"></i>
                        </a>
                    </li>
                    {% endif %}
                </ul>
            </nav>
            {% endif %}
            <!-- END Pagination -->
        </div>
    </div>

        </div>
 <div class="text-center fs-6">
    <a href="{% url 'users:dashboard' %}">Back to Dashboard</a>
</div>
</div>
{% endblock %}